#!/usr/bin/env bun
/**
 * Generate the checked-in Anthropic Mono cmap coverage table.
 *
 * Usage:
 *   bun scripts/generate-font-coverage.ts /path/to/AnthropicMono-*.ttf
 *
 * All supplied faces must have identical coverage. This is intentionally a
 * developer-only generator: the external font files are not build inputs.
 */

import { createHash } from "crypto";
import { basename } from "path";
import { readFileSync, writeFileSync } from "fs";

const OUTPUT_FILE = "client/src/terminal/anthropicMonoCoverage.generated.ts";

type CodepointRange = readonly [number, number];

function queryCharset(path: string): CodepointRange[] {
  const result = Bun.spawnSync(["fc-query", "-f", "%{charset}\n", path], {
    stdout: "pipe",
    stderr: "pipe",
  });
  if (result.exitCode !== 0) {
    const error = result.stderr.toString().trim();
    throw new Error(`fc-query failed for ${path}${error ? `: ${error}` : ""}`);
  }

  const codepoints = new Set<number>();
  for (const token of result.stdout.toString().trim().split(/\s+/)) {
    if (!token) continue;
    const match = /^([0-9a-f]+)(?:-([0-9a-f]+))?$/i.exec(token);
    if (!match) {
      throw new Error(`Unexpected fc-query charset token '${token}' for ${path}`);
    }
    const start = Number.parseInt(match[1]!, 16);
    const end = match[2] ? Number.parseInt(match[2], 16) : start;
    for (let codepoint = start; codepoint <= end; codepoint++) {
      codepoints.add(codepoint);
    }
  }

  const sorted = [...codepoints].sort((a, b) => a - b);
  const ranges: CodepointRange[] = [];
  for (const codepoint of sorted) {
    const previous = ranges.at(-1);
    if (previous && codepoint === previous[1] + 1) {
      ranges[ranges.length - 1] = [previous[0], codepoint];
    } else {
      ranges.push([codepoint, codepoint]);
    }
  }
  return ranges;
}

function rangeKey(ranges: CodepointRange[]): string {
  return ranges.map(([start, end]) => `${start.toString(16)}-${end.toString(16)}`).join(" ");
}

function hex(codepoint: number): string {
  return `0x${codepoint.toString(16).toUpperCase()}`;
}

const fontPaths = process.argv.slice(2);
if (fontPaths.length === 0) {
  throw new Error("Pass one or more Anthropic Mono TTF paths");
}

const coverage = queryCharset(fontPaths[0]!);
const expectedKey = rangeKey(coverage);
for (const path of fontPaths.slice(1)) {
  const candidate = queryCharset(path);
  if (rangeKey(candidate) !== expectedKey) {
    throw new Error(`Coverage differs between ${fontPaths[0]} and ${path}`);
  }
}

const codepointCount = coverage.reduce((total, [start, end]) => total + end - start + 1, 0);
const sources = fontPaths
  .map((path) => {
    const digest = createHash("sha256").update(readFileSync(path)).digest("hex");
    return `// - ${basename(path)} sha256:${digest}`;
  })
  .join("\n");
const rangeLines = coverage
  .map(([start, end]) => `  [${hex(start)}, ${hex(end)}],`)
  .join("\n");

const output = `// Generated by scripts/generate-font-coverage.ts. DO NOT EDIT.\n// Sources:\n${sources}\n// Coverage: ${codepointCount} codepoints in ${coverage.length} ranges.\n\nexport const ANTHROPIC_MONO_CODEPOINT_COUNT = ${codepointCount};\nexport const ANTHROPIC_MONO_RANGE_COUNT = ${coverage.length};\n\nexport const ANTHROPIC_MONO_RANGES: readonly (readonly [number, number])[] = [\n${rangeLines}\n];\n`;

writeFileSync(OUTPUT_FILE, output);
console.log(`Wrote ${OUTPUT_FILE}: ${codepointCount} codepoints in ${coverage.length} ranges`);
